name: Pull test package (public)
on: push

jobs:
 all:
  runs-on: self-hosted
  
  steps:
   - name: Login to GitHub container Registry
     run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin 
   - name: Tag the image
     run: docker pull ghcr.io/kaminipandey/docker-workflow-test/centos12:123cent
